# Generated by Django 5.2.13 on 2026-04-12 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الثلاثي')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('weight_kg', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الوزن (كجم)')),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الطول (سم)')),
                ('education', models.CharField(choices=[('none', 'بدون مؤهل'), ('below_avg', 'متوسط'), ('above_avg', 'فوق المتوسط'), ('university', 'جامعي'), ('postgrad', 'دراسات عليا')], default='university', max_length=32, verbose_name='المؤهل')),
                ('job_title', models.CharField(blank=True, max_length=300, verbose_name='الوظيفة')),
                ('governorate', models.CharField(max_length=64, verbose_name='المحافظة')),
                ('marital_status', models.CharField(choices=[('single', 'أعزب/عزباء'), ('engaged', 'سبق عقد/كتب كتاب'), ('divorced', 'مطلق/مطلقة'), ('widowed', 'أرمل/أرملة'), ('polygamy', 'متزوج يرغب في الزوجة الثانية')], max_length=32)),
                ('residence_summary', models.CharField(max_length=300, verbose_name='محل الإقامة (بلد - محافظة - مدينة)')),
                ('about_me', models.TextField(blank=True, verbose_name='نبذة عني والأهل')),
                ('partner_specs', models.TextField(blank=True, verbose_name='مواصفات شريك الحياة المطلوبة')),
                ('quran_parts', models.PositiveSmallIntegerField(default=0, verbose_name='أجزاء الحفظ')),
                ('preferred_partner_age_min', models.PositiveSmallIntegerField(default=18)),
                ('preferred_partner_age_max', models.PositiveSmallIntegerField(default=50)),
                ('whatsapp_phone', models.CharField(blank=True, max_length=32, verbose_name='واتساب')),
                ('telegram_username', models.CharField(blank=True, max_length=120, verbose_name='تليجرام')),
                ('facebook_url', models.CharField(blank=True, max_length=300, verbose_name='فيسبوك')),
                ('applicant_gender', models.CharField(choices=[('male', 'ذكر (عريس)'), ('female', 'أنثى (عروس)')], max_length=16)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف مقدّم الطلب',
                'verbose_name_plural': 'ملفات مقدّمي الطلبات',
            },
        ),
        migrations.CreateModel(
            name='BrideExtendedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_mother_work', models.CharField(blank=True, max_length=300, verbose_name='عمل الوالدين')),
                ('siblings_summary', models.CharField(blank=True, max_length=300, verbose_name='الأخوات والكليات')),
                ('parents_separated', models.BooleanField(default=False, verbose_name='انفصال الوالدين')),
                ('hijab_type', models.CharField(blank=True, max_length=120, verbose_name='نوع الحجاب')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bride_extra', to='profiles.applicantprofile')),
            ],
            options={
                'verbose_name': 'بيانات إضافية (عروس)',
            },
        ),
        migrations.CreateModel(
            name='GroomExtendedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expat', models.BooleanField(default=False, verbose_name='مغترب')),
                ('take_abroad', models.BooleanField(default=False, verbose_name='نية السفر بالزوجة')),
                ('smokes', models.BooleanField(default=False)),
                ('polygamy_notes', models.TextField(blank=True, verbose_name='تفاصيل التعدد')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groom_extra', to='profiles.applicantprofile')),
            ],
            options={
                'verbose_name': 'بيانات إضافية (عريس)',
            },
        ),
        migrations.CreateModel(
            name='ProfileMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profiles/%Y/%m/')),
                ('review_status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=16)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='profiles.applicantprofile')),
            ],
            options={
                'verbose_name': 'مرفق ملف',
                'verbose_name_plural': 'مرفقات الملفات',
            },
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['governorate', 'marital_status'], name='profiles_ap_governo_f3f9bb_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['applicant_gender'], name='profiles_ap_applica_020614_idx'),
        ),
    ]
