# Generated by Django 5.2.13 on 2026-04-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='preferred_partner_age_max',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='الحد الأعلى لعمر شريك الحياة المطلوب'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='preferred_partner_age_min',
            field=models.PositiveSmallIntegerField(default=18, verbose_name='الحد الأدنى لعمر شريك الحياة المطلوب'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='quran_parts',
            field=models.PositiveSmallIntegerField(default=0, help_text='عدد الأجزاء الثلاثين التي تحفظها من القرآن الكريم (0 إن لم يكن هناك حفظ).', verbose_name='مقدار الحفظ من القرآن'),
        ),
        migrations.AlterField(
            model_name='groomextendedprofile',
            name='smokes',
            field=models.BooleanField(default=False, verbose_name='مدخن؟'),
        ),
    ]
