# Generated by Django 5.2.13 on 2026-04-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_applicantprofile_preferred_partner_age_max_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileMedia',
        ),
    ]
