# Generated by Django 5.2 style migration for email verification

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="تاريخ تأكيد البريد",
            ),
        ),
        migrations.CreateModel(
            name="EmailVerificationPending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("last_sent_at", models.DateTimeField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_pending",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "رمز تأكيد بريد معلّق",
                "verbose_name_plural": "رموز تأكيد بريد معلّقة",
            },
        ),
    ]
