# Generated by Django 5.2.13 on 2026-04-12 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroductionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الطرف الآخر'), ('accepted_by_recipient', 'مقبول من الطرف الآخر'), ('pending_moderator', 'بانتظار المشرف'), ('approved', 'موافقة المشرف'), ('rejected', 'رفض المشرف')], default='pending', max_length=32)),
                ('message', models.TextField(blank=True, verbose_name='رسالة مختصرة')),
                ('moderator_notes', models.TextField(blank=True, verbose_name='ملاحظات المشرف')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intro_decisions', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intro_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intro_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طلب تعارف / رؤية شرعية',
                'verbose_name_plural': 'طلبات التعارف',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('requester', 'recipient'), name='unique_intro_pair')],
            },
        ),
    ]
