# قيم مخزّنة في DB (إنجليزي قصير) + عرض عربي في الواجهة
EGYPT_GOVERNORATES = (
    ("cairo", "القاهرة"),
    ("giza", "الجيزة"),
    ("alexandria", "الإسكندرية"),
    ("dakahlia", "الدقهلية"),
    ("sharqia", "الشرقية"),
    ("qalyubia", "القليوبية"),
    ("gharbia", "الغربية"),
    ("monufia", "المنوفية"),
    ("beheira", "البحيرة"),
    ("kafr_el_sheikh", "كفر الشيخ"),
    ("damietta", "دمياط"),
    ("port_said", "بورسعيد"),
    ("ismailia", "الإسماعيلية"),
    ("suez", "السويس"),
    ("north_sinai", "شمال سيناء"),
    ("south_sinai", "جنوب سيناء"),
    ("beni_suef", "بني سويف"),
    ("fayoum", "الفيوم"),
    ("minya", "المنيا"),
    ("asyut", "أسيوط"),
    ("sohag", "سوهاج"),
    ("qena", "قنا"),
    ("luxor", "الأقصر"),
    ("aswan", "أسوان"),
    ("red_sea", "البحر الأحمر"),
    ("new_valley", "الوادي الجديد"),
    ("matrouh", "مطروح"),
)
